package com.example.dsp

/** Bronlijst; dezelfde scenes staan ook in ListeningScenes.ALL + GROUPS. */
object ExtraListeningScenes {
    val ALL = listOf(
        ListeningScene("house", "House", "🏠", "Vier-op-de-vloer + warme bas", "Electronic & Festival EDM", AncMode.ADAPTIVE),
        ListeningScene("techno", "Techno", "🔲", "Droge kick + tight hoog", "Electronic & Festival EDM", AncMode.ADAPTIVE),
        ListeningScene("dubstep", "Dubstep", "🌀", "Zware wobble + sub", "Hip-Hop & Urban R&B", AncMode.ADAPTIVE),
        ListeningScene("ambient", "Ambient", "🌫️", "Zacht, ruimtelijk, veilig", "Night Chill & Lo-Fi Relax", AncMode.OFF, safeVolume = true),
        ListeningScene("saver", "Saver", "🔋", "Lage accu: zacht + LDAC 330", "Night Chill & Lo-Fi Relax", AncMode.OFF, safeVolume = true, preferredLdac = LdacQualityMode.CONNECTION_330),
        ListeningScene("radio", "Radio", "📻", "Stem + muziek, lichte ANC", "Vocal & Acoustic Warmth", AncMode.ADAPTIVE),
        ListeningScene("tv", "TV", "📺", "Dialoog voorop + lichte bas", "Vocal & Acoustic Warmth", AncMode.ADAPTIVE),
        ListeningScene("djset", "DJ-set", "🎛️", "Lange mix, punch + glitter", "Electronic & Festival EDM", AncMode.ADAPTIVE),
        ListeningScene("liquid", "Liquid DnB", "💧", "Zachte rolling bass + vocaal", "Night Chill & Lo-Fi Relax", AncMode.ADAPTIVE),
        ListeningScene("lecture", "College", "🧑‍🏫", "Spraakhelder + veilig", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("commute_rain", "Pendelen regen", "☔", "Max ANC + warme mids", "Philips TAH6519 Pro ANC", AncMode.STRONG, preferredLdac = LdacQualityMode.BALANCED_660),
        ListeningScene("morning", "Ochtend", "🌅", "Warme mids, zachte start", "Vocal & Acoustic Warmth", AncMode.ADAPTIVE),
        ListeningScene("basscheck", "Bass-check", "📢", "Sub + kick om laag te testen", "Hip-Hop & Urban R&B", AncMode.OFF),
        ListeningScene("stereotest", "Stereo-test", "↔️", "Links/rechts + breedte", "Classical & Live Concert 3D", AncMode.OFF),
        ListeningScene("reference", "Referentie", "🎚️", "Vlak A/B zonder extra DSP", "Flat Studio Monitor (0 dB)", AncMode.OFF),
        ListeningScene("speaker", "Speaker", "🔈", "Speaker-achtig: minder stereo-split", "Vocal & Acoustic Warmth", AncMode.OFF),
        ListeningScene("studio", "Studio", "🎛️", "Vlak + helder, mix-check", "Flat Studio Monitor (0 dB)", AncMode.OFF),
        ListeningScene("nightshift", "Nachtdienst", "🌃", "Zacht + alert + veilig", "Night Chill & Lo-Fi Relax", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("market", "Markt", "🛒", "Transparantie in de drukte", "Vocal & Acoustic Warmth", AncMode.AMBIENT),
        ListeningScene("interview", "Interview", "🎙️", "Stem max, geen bas, veilig", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("mixcheck", "Mix-check", "🧪", "Vlak + limiter uit, A/B-ready", "Flat Studio Monitor (0 dB)", AncMode.OFF),
        ListeningScene("flightsleep", "Vlucht-slaap", "🛬", "Max ANC + zacht + sleep-vriendelijk", "Night Chill & Lo-Fi Relax", AncMode.STRONG, safeVolume = true),
        ListeningScene("piano", "Piano", "🎹", "Mids + ruimte, geen extra bas", "Classical & Live Concert 3D", AncMode.OFF),
        ListeningScene("acoustic", "Akoestisch", "🎸", "Warme stem + gitaar", "Vocal & Acoustic Warmth", AncMode.OFF),
        ListeningScene("wind", "Wind", "💨", "Sterk windfilter + alert", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD),
        ListeningScene("bike_rain", "Fiets-regen", "🚲", "Wind + ANC tegen regen", "Philips TAH6519 Pro ANC", AncMode.STRONG),
        ListeningScene("recap", "Recap", "⏪", "Laatst gebruikte scene herhalen", "Flat Studio Monitor (0 dB)", AncMode.ADAPTIVE),
        ListeningScene("coding", "Code", "💻", "Focus + zachte ANC, veilig", "Night Chill & Lo-Fi Relax", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("cardio", "Cardio", "🏃", "Punch + ademruimte buiten", "Electronic & Festival EDM", AncMode.WIND_GUARD),
        ListeningScene("yoga", "Yoga", "🧘", "Zacht + ruimtelijk + veilig", "Night Chill & Lo-Fi Relax", AncMode.OFF, safeVolume = true),
        ListeningScene("nav", "Navigatie", "📍", "Stemhelder + lichte ANC", "Vocal & Acoustic Warmth", AncMode.AMBIENT),
        ListeningScene("language", "Taal", "🌍", "Spraakmax + veilig", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("shortform", "Shorts", "⚡", "Korte clips: punch + helder, geen zware ANC", "Electronic & Festival EDM", AncMode.ADAPTIVE),
        ListeningScene("garden", "Tuin", "🌱", "Buiten alert + windfilter", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD),
        ListeningScene("waiting", "Wachten", "⏳", "Zacht + veilig in de rij", "Night Chill & Lo-Fi Relax", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("nightdrive", "Nacht-auto", "🌃", "Lage latency + minder hoog", "Rock & Metal Punch", AncMode.WIND_GUARD, preferredCodec = BluetoothCodec.APTX_ADAPTIVE),
        ListeningScene("rainwalk", "Regenwandeling", "💦", "ANC + wind + warme mids", "Philips TAH6519 Pro ANC", AncMode.STRONG),
        ListeningScene("festival", "Festival", "🎪", "Hard buiten + wind + punch", "Electronic & Festival EDM", AncMode.WIND_GUARD),
        ListeningScene("ferry", "Veerboot", "⛴️", "ANC tegen motor + wind", "Philips TAH6519 Pro ANC", AncMode.STRONG),
        ListeningScene("workshop", "Klus", "🔧", "Alert + ANC tegen machines", "Vocal & Acoustic Warmth", AncMode.AMBIENT),
        ListeningScene("cowork", "Cowork", "🪑", "Focus + lichte ANC, veilig", "Flat Studio Monitor (0 dB)", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("barber", "Kapper", "✂️", "Alert + spraak, veilig", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("dentist", "Tandarts", "🦷", "Max ANC + veilig volume", "Night Chill & Lo-Fi Relax", AncMode.STRONG, safeVolume = true),
        ListeningScene("sauna", "Sauna", "🧖", "Zacht + ruimtelijk + veilig", "Night Chill & Lo-Fi Relax", AncMode.OFF, safeVolume = true),
        ListeningScene("stadium", "Stadion", "📣", "Commentaar + crowd punch", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD),
        ListeningScene("museumtour", "Audiotour", "🎧", "Spraakmax + alert, veilig", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("camping", "Camping", "⛺", "Wind + natuur + alert, veilig", "Night Chill & Lo-Fi Relax", AncMode.WIND_GUARD, safeVolume = true),
        ListeningScene("exam", "Tentamen", "📝", "Diepe focus + veilig volume", "Flat Studio Monitor (0 dB)", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("karaoke", "Karaoke", "🎤", "Stem max + lichte bas", "Vocal & Acoustic Warmth", AncMode.OFF),
        ListeningScene("baby", "Baby", "🍼", "Ultra-zacht + alert + veilig", "Night Chill & Lo-Fi Relax", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("alert", "Alert", "🔔", "Max transparantie, deurbel/omgeving", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("pool", "Zwembad", "🏊", "Wind + water, alert, veilig", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD, safeVolume = true),
        ListeningScene("playground", "Schoolplein", "🛝", "Kids-alert + veilig volume", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("photoshoot", "Fotoshoot", "📷", "Zacht + alert, geen zware bas", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("callcenter", "Callcenter", "☎️", "Stem max + lichte ANC, veilig", "Vocal & Acoustic Warmth", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("livestream", "Livestream", "📡", "Commentaar + punch, lage latency", "Vocal & Acoustic Warmth", AncMode.ADAPTIVE, preferredCodec = BluetoothCodec.APTX_ADAPTIVE),
        ListeningScene("ereader", "E-reader", "📱", "Fluister-EQ, veilig lezen", "Night Chill & Lo-Fi Relax", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("quietcar", "Stiltecoupé", "🤫", "Max ANC, fluister, veilig", "Night Chill & Lo-Fi Relax", AncMode.STRONG, safeVolume = true),
        ListeningScene("park", "Park", "🌳", "Windfilter + alert buiten", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD, safeVolume = true),
        ListeningScene("videocall", "Videobellen", "📹", "Stem max + lichte ANC", "Vocal & Acoustic Warmth", AncMode.AMBIENT, preferredCodec = BluetoothCodec.APTX_ADAPTIVE),
        ListeningScene("esports", "Esports", "🏆", "Footsteps + lage latency", "Rock & Metal Punch", AncMode.AMBIENT, preferredCodec = BluetoothCodec.APTX_ADAPTIVE),
        ListeningScene("movienight", "Filmavond", "🌃", "Breed stereo, zachte loudness", "Classical & Live Concert 3D", AncMode.STRONG, safeVolume = true),
        ListeningScene("ski", "Ski", "🎿", "Wind + punch + alert", "Electronic & Festival EDM", AncMode.WIND_GUARD),
        ListeningScene("radio_nl", "NPO Radio", "🇳🇱", "Stem + muziek NL", "Vocal & Acoustic Warmth", AncMode.ADAPTIVE),
        ListeningScene("bioscoop", "Bioscoop", "🎥", "Breed stereo + lichte ANC", "Classical & Live Concert 3D", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("terras", "Terras", "🥂", "Alert + warme stemmen buiten", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD, safeVolume = true),
        ListeningScene("pretpark", "Pretpark", "🎢", "Wind + punch + alert", "Electronic & Festival EDM", AncMode.WIND_GUARD),
        ListeningScene("hackathon", "Hackathon", "⌨️", "Lange focus + veilig", "Flat Studio Monitor (0 dB)", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("mall", "Winkelcentrum", "🏬", "Transparantie in de hal", "Vocal & Acoustic Warmth", AncMode.AMBIENT),
        ListeningScene("douane", "Douane", "🛂", "Alert + ANC tegen hal", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("gvb", "GVB/RET", "🚌", "Stadsvervoer ANC + stem", "Philips TAH6519 Pro ANC", AncMode.STRONG, preferredLdac = LdacQualityMode.BALANCED_660),
        ListeningScene("nightmarket", "Nachtmarkt", "🏮", "Alert + warme mids", "Vocal & Acoustic Warmth", AncMode.AMBIENT),
        ListeningScene("lofi", "Lo-fi", "📻", "Zacht + veilig studeren", "Night Chill & Lo-Fi Relax", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("library", "Bibliotheek", "📚", "Fluister + max ANC, veilig", "Night Chill & Lo-Fi Relax", AncMode.STRONG, safeVolume = true),
        ListeningScene("concertzaal", "Concertzaal", "🏛️", "Breed 3D + dynamiek", "Classical & Live Concert 3D", AncMode.OFF),
        ListeningScene("horeca", "Horeca", "🍴", "Stemmen + alert in zaak", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("ikea", "IKEA", "🪑", "Hal-ruis + navigatie-stem", "Vocal & Acoustic Warmth", AncMode.AMBIENT),
        ListeningScene("wfh", "Thuiswerken", "🏠", "Focus + lichte ANC, veilig", "Flat Studio Monitor (0 dB)", AncMode.ADAPTIVE, safeVolume = true),
        ListeningScene("treinwerk", "Treinwerk", "💻", "Focus + ANC tegen rails, veilig", "Flat Studio Monitor (0 dB)", AncMode.STRONG, safeVolume = true, preferredLdac = LdacQualityMode.BALANCED_660),
        ListeningScene("nsdruk", "Drukke NS", "🚃", "Max ANC + stemmen in volle trein", "Philips TAH6519 Pro ANC", AncMode.STRONG, preferredLdac = LdacQualityMode.BALANCED_660),
        ListeningScene("ovchip", "OV-chip", "🎫", "Alert bij in-/uitchecken", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("swapfiets", "Swapfiets", "🚲", "Windfilter + alert in verkeer", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD),
        ListeningScene("collegezaal", "Collegezaal", "🏫", "Spraakmax + veilig in zaal", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("praat", "Gesprek", "💬", "Max transparantie, geen bas", "Vocal & Acoustic Warmth", AncMode.AMBIENT, safeVolume = true),
        ListeningScene("marktplein", "Marktplein", "🧺", "Alert + warme stemmen buiten", "Vocal & Acoustic Warmth", AncMode.WIND_GUARD, safeVolume = true),
        ListeningScene("basicfit", "Basic-Fit", "🏋️", "Kick + ANC in de gym", "Electronic & Festival EDM", AncMode.STRONG)
    )

    val GENRE_IDS = setOf("house", "techno", "dubstep", "ambient", "djset", "liquid")
    val MEDIA_IDS = setOf("radio", "tv", "djset", "speaker", "reference", "studio", "shortform", "piano", "acoustic", "museumtour", "karaoke", "livestream", "ereader", "movienight", "radio_nl", "bioscoop", "lofi", "concertzaal")
    val NIGHT_IDS = setOf("ambient", "saver", "liquid", "nightshift", "yoga", "nightdrive", "flightsleep", "sauna", "camping", "baby", "movienight", "quietcar", "nightmarket", "lofi")
    val WORK_IDS = setOf("lecture", "coding", "interview", "language", "waiting", "workshop", "cowork", "exam", "callcenter", "videocall", "hackathon", "library", "wfh", "collegezaal", "treinwerk", "praat")
    val COMMUTE_IDS = setOf("commute_rain", "wind", "bike_rain", "nav", "rainwalk", "nightdrive", "ferry", "quietcar", "gvb", "douane", "ovchip", "swapfiets", "treinwerk", "nsdruk")
    val TOOL_IDS = setOf("basscheck", "stereotest", "reference", "speaker", "studio", "mixcheck", "recap")
    val DAY_IDS = setOf("morning", "market", "coding", "yoga", "garden", "waiting", "barber", "cowork", "alert", "camping", "playground", "photoshoot", "pool", "park", "terras", "mall", "horeca", "ikea", "marktplein", "praat")
    val SPORT_IDS = setOf("cardio", "yoga", "festival", "stadium", "pool", "ski", "esports", "pretpark", "basicfit")
}
